### ISSUE TITLE
try to generator a action , but get error

### ISSUE THREAD

**Issue by Wolke** [yoichiro/generator-action#26]
yo action
========

module.js:491
    throw err;
    ^

Error: Cannot find module 'duplexify'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/got/index.js:8:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by yoichiro** [comment]
@Wolke It is not enough information to fix your issue. Can you provide me like the following information?

* What did you want to do? Or, what did you do?
* How was the steps to reproduce your issue?
* What behavior did you expect?
* What behavior did you face in fact?
* How was the environment when you faced this issue?

**Comment by Wolke** [comment]
after use node 10.
its work
